# Generated by Django 4.0.1 on 2022-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldetails',
            name='annual_turnover',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='avg_monthly_income',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='company_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='designation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='itr',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='mode_of_salary',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='ONLINE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='monthly_income',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='type_employment',
            field=models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF-SALARIED', 'Self-Salaried')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='year_of_exp',
            field=models.FloatField(null=True),
        ),
    ]
