# Generated by Django 4.0.1 on 2022-01-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('LoanApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedloan',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
