# Generated by Django 4.0.1 on 2022-01-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('AddressApp', '0002_alter_currentaddress_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
